name: hi

on: [push]

jobs:
  bob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mgwalker/check-internal-links-action@efbbce1ea69061fbb26662ae2ab7bdb3a9ea9290
        with:
          path: pages
          # baseUrl: https://testing.com
          # ignore:
          #   - /admin/**/*
