name: hi

on: [push]

jobs:
  bob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mgwalker/check-internal-links-action@4db47d45ccf58b00a6ceda98e820d7d2e643314f
        with:
          path: pages
          # baseUrl: https://testing.com
          # ignore:
          #   - /admin/**/*
