name: htmlproofer

on: [push]

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mgwalker/check-internal-links-action@693f8ef62a1ddabe04827b99d8ae1166252041ae
        with:
          path: pages
          # baseUrl: https://testing.com
          # ignore:
          #   - /admin/**/*
