name: htmlproofer

on: [push]

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mgwalker/check-internal-links-action@8b19cbf65f454a88a4ed93d226e9117579ff9a4b
        with:
          path: pages
          # baseUrl: https://testing.com
          # ignore:
          #   - /admin/**/*
